version: "3.8"

services:
  mariadb:
    image: mariadb:10.5
    container_name: koha-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: koha_root_password
      MYSQL_DATABASE: koha
      MYSQL_USER: kohauser
      MYSQL_PASSWORD: kohapass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - kohanet
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "mariadb",
          "-u",
          "root",
          "-p$$MYSQL_ROOT_PASSWORD",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "4406:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.18
    container_name: koha-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - kohanet

  koha:
    image: digibib/koha:latest
    platform: linux/amd64
    container_name: koha-app
    depends_on:
      mariadb:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    environment:
      KOHA_INSTANCE: library
      KOHA_ADMINUSER: kohaadmin
      KOHA_ADMINPASS: adminpass
      KOHA_DB_HOST: mariadb
      KOHA_DB_NAME: koha
      KOHA_DB_USER: kohauser
      KOHA_DB_PASS: kohapass
      KOHA_ELASTICSEARCH: http://elasticsearch:9200
      KOHA_OPAC_PORT: 8082
      KOHA_INTRANET_PORT: 8081
      DB_HOST: mariadb
      DB_NAME: koha
      DB_USER: kohauser
      DB_PASS: kohapass
    ports:
      - "8081:8081" # Koha staff interface
      - "8082:8082" # Koha OPAC
    volumes:
      - koha_data:/data
    networks:
      - kohanet

volumes:
  mariadb_data:
  esdata:
  koha_data:

networks:
  kohanet:
    driver: bridge
